# Translation dictionary: Portuguese column name -> English column name
# Tha naming is improved for clarity where possible
translation_dict = {
    "DISTRITO": "DISTRICT",
    "TIPO": "WILDFIRE_TYPE",
    "ANO": "YEAR",
    "AREAPOV": "BURNED_POPULATIONAL_AREA",
    "AREAMATO": "BURNED_BRUSHLAND_AREA",
    "AREAAGRIC": "BURNED_AGRICULTURAL_AREA",
    "AREATOTAL": "BURNED_TOTAL_AREA",
    "REACENDIMENTOS": "IS_A_REIGNITION",
    "FOGACHO": "IS_A_SMALL_FIRE",
    "INCENDIO": "IS_A_WILDFIRE",
    "AGRICOLA": "IS_A_AGRICULTURAL_FIRE",
    "NCCO": "LOCAL_COMMAND_CENTER_CODE",
    "NOMECCO": "REGIONAL_COMMAND_CENTER_CODE",
    "DATAALERTA": "ALERT_DATE",
    "HORAALERTA": "ALERT_TIME",
    "LOCAL": "LOCATION",
    "CONCELHO": "MUNICIPALITY",
    "FREGUESIA": "PARISH",
    "FONTEALERTA": "ALERT_SOURCE",
    "INE": "MUNICIPALITY_CODES",
    "X": "X_PORT_COORD",
    "Y": "Y_PORT_COORD",
    "DIA": "DAY",
    "MES": "MONTH",
    "HORA": "HOUR",
    "OPERADOR": "OPERATOR",
    "CAUSA": "CAUSE",
    "TIPOCAUSA": "CAUSE_TYPE",
    "DHINICIO": "START_DATETIME",
    "DHFIM": "END_DATETIME",
    "DURACAO": "DURATION_MINUTES",
    "HAHORA": "HECTARES_PER_HOUR",
    "DATAEXTINCAO": "EXTINCTION_DATE",
    "HORAEXTINCAO": "EXTINCTION_TIME",
    "DATA1INTERVENCAO": "FIRST_INTERVENTION_DATE",
    "HORA1INTERVENCAO": "FIRST_INTERVENTION_TIME",
    "QUEIMA": "IS_A_CONTROLLED_FIRE",
    "LAT": "LATITUDE",
    "LON": "LONGITUDE",
    "CAUSAFAMILIA": "CAUSE_FAMILY",
    "TEMPERATURA": "TEMPERATURE_CELSIUS",
    "HUMIDADERELATIVA": "RELATIVE_HUMIDITY_PERCENT",
    "VENTOINTENSIDADE": "WIND_SPEED_MS",
    "VENTOINTENSIDADE_VETOR": "WIND_SPEED_VECTOR",
    "VENTODIRECAO_VETOR": "WIND_DIRECTION_VECTOR",
    "PRECEPITACAO": "PRECIPITATION_MM",
    "FFMC": "FFMC",
    "DMC": "DMC",
    "DC": "DC",
    "ISI": "ISI",
    "BUI": "BUI",
    "FWI": "FWI",
    "DSR": "DSR",
    "THC": "THC",
    "MODFARSITE": "MODELED_BURNED_AREA_FARSITE_HA",
    "ALTITUDEMEDIA": "MEAN_ALTITUDE_M",
    "DECLIVEMEDIO": "MEAN_SLOPE_DEG",
    "DENDIDADERV": "VEGETATION_DENSITY",
    "COSN5VARIEDADE": "VEGETATION_VARIETY_INDEX",
    "AREAMANCHAMODFARSITE": "BURNED_PATCH_AREA_FARSITE_HA",
}
# │ Florestal     ┆ 113669 │
# │ Agrícola      ┆ 29718  │
# │ Queima        ┆ 16     │
wildfire_type_translation_dict = {
    "Florestal": "Wildfire",
    "Agrícola": "Agricultural",
    "Queima": "Controlled",
}
# │ Reacendimento ┆ 10037 │
# │ null          ┆ 22382 │
# │ Natural       ┆ 1166  │
# │ Intencional   ┆ 23954 │
# │ Desconhecida  ┆ 43359 │
# │ Negligente    ┆ 42505 │
cause_type_translation_dict = {
    "Desconhecida": "Unknown",
    "Negligente": "Negligent",
    "Intencional": "Intentional",
    "Reacendimento": "Reignition",
    "Natural": "Natural",
    None: "Unknown",
}

# │ 117          ┆ 16924 │
# │ null         ┆ 12321 │
# │ Outros       ┆ 18553 │
# │ 112          ┆ 13336 │
# │ PV           ┆ 10390 │
# │ Sapadores    ┆ 1811  │
# │ CCO          ┆ 7481  │
# │ Populares    ┆ 62587 │
alert_source_translation_dict = {
    "Populares": "Public",
    "CCO": "Command Center",
    "Sapadores": "Firefighters",
    "PV": "Fire Watch Tower",
    "Outros": "Other",
    "117": "Military",
    "112": "Police",
    None: "Unknown",
}

# Detailed cause codes dictionary
fire_cause_codes = {
    "11": "Use of fire",
    "111": "Municipal waste burning",
    "112": "Industry waste burning",
    "113": "Commercial waste burning",
    "114": "Illegal activities waste burning",
    "115": "Permanent residential waste burning",
    "116": "Temporary residential waste burning",
    "12": "Prescribed burns",
    "121": "Agricultural land clearing",
    "122": "Forest land clearing",
    "123": "Urban area clearing",
    "124": "Burn piles (agricultural/moorland)",
    "125": "Pasture renewal",
    "126": "Hunting/fishing area penetration",
    "127": "Path/road/access clearing",
    "128": "Fire protection (incorrect use)",
    "129": "Other prescribed burns",
    "13": "Firework launching",
    "131": "With preventive measures",
    "132": "Clanestine (no measures)",
    "133": "Auto-ignition (firework remnants)",
    "14": "Bonfires",
    "141": "Recreation and leisure",
    "142": "Food cooking",
    "143": "Heating",
    "144": "Road repair",
    "145": "Other bonfires",
    "15": "Smoking",
    "151": "Smokers on foot",
    "152": "Smokers in motor vehicles",
    "16": "Beekeeping",
    "161": "Bee smoker use",
    "162": "Disinfestation",
    "17": "Chimneys",
    "171": "Industrial chimneys",
    "172": "Residential chimneys",
    "173": "Other chimneys",
    "2": "Accidental",
    "21": "Transport and communications",
    "211": "Power lines",
    "212": "Railways",
    "213": "Exhaust pipes",
    "214": "Traffic accidents",
    "215": "Other transport accidents",
    "22": "Machinery and equipment",
    "221": "Agricultural tools",
    "222": "Agricultural machinery",
    "223": "Forestry equipment",
    "224": "Chainsaws",
    "225": "Forestry machinery",
    "226": "Industrial machinery",
    "227": "Other machinery and equipment",
    "23": "Other accidental causes",
    "231": "Explosives (civil use)",
    "232": "Welding",
    "233": "Hunter gunshots",
    "234": "Military exercises",
    "235": "Glass (lens effect)",
    "236": "Other accidental causes",
    "3": "Structural",
    "31": "Hunting and wildlife",
    "311": "Hunting conflicts",
    "312": "Wildlife damage retaliation",
    "33": "Land use",
    "333": "Land use changes",
    "334": "Pressure to sell wood",
    "335": "Land use/management limitations",
    "336": "Common land use conflicts",
    "37": "Fire defense",
    "337": "DFCI labor instability",
    "38": "Other structural causes",
    "4": "Arson",
    "41": "Non-imputable",
    "412": "Children's play",
    "413": "Minor irresponsibility",
    "417": "Pyromania",
    "419": "Other non-imputable situations",
    "44": "Imputable",
    "441": "Diversion maneuvers",
    "444": "Provocation of firefighting means",
    "445": "Neighbor conflicts",
    "446": "Revenge",
    "448": "Vandalism",
    "449": "Other intentional situations",
    "5": "Natural",
    "51": "Lightning",
    "6": "Undetermined",
    "60": "Undetermined",
    "610": "Material evidence undetermined",
    "620": "Personal evidence undetermined",
    "630": "Other information undetermined",
}
